-- carga_100_registros.sql
-- Finalidade: inserir uma massa ficticia e consistente para o sistema Starforge.
-- Instrucao: executar apos ddl/schema.sql. O script cria mais de 100 registros
-- respeitando PKs, FKs, restricoes CHECK e indices unicos.

SET DEFINE OFF;

INSERT ALL
  INTO TB_AGENCIA (ID_AGENCIA, NM_AGENCIA) VALUES ('AGE-001', 'Agencia Orbital Brasileira')
  INTO TB_AGENCIA (ID_AGENCIA, NM_AGENCIA) VALUES ('AGE-002', 'Agencia Espacial Andina')
  INTO TB_AGENCIA (ID_AGENCIA, NM_AGENCIA) VALUES ('AGE-003', 'Consorcio Lunar Atlantico')
  INTO TB_AGENCIA (ID_AGENCIA, NM_AGENCIA) VALUES ('AGE-004', 'Observatorio Espacial Sul')
  INTO TB_AGENCIA (ID_AGENCIA, NM_AGENCIA) VALUES ('AGE-005', 'Instituto Helios')
SELECT 1 FROM DUAL;

INSERT ALL
  INTO TB_ORGANIZACAO (ID_ORGANIZACAO, NM_ORGANIZACAO) VALUES ('ORG-001', 'EcoSat Labs')
  INTO TB_ORGANIZACAO (ID_ORGANIZACAO, NM_ORGANIZACAO) VALUES ('ORG-002', 'Amazonia Viva Tech')
  INTO TB_ORGANIZACAO (ID_ORGANIZACAO, NM_ORGANIZACAO) VALUES ('ORG-003', 'Mar Azul Analytics')
  INTO TB_ORGANIZACAO (ID_ORGANIZACAO, NM_ORGANIZACAO) VALUES ('ORG-004', 'AgroOrbital')
  INTO TB_ORGANIZACAO (ID_ORGANIZACAO, NM_ORGANIZACAO) VALUES ('ORG-005', 'Defesa Civil Cosmos')
SELECT 1 FROM DUAL;

INSERT ALL
  INTO TB_TIER (ID_TIER, NM_TIER, VL_MIN_TIER, FL_ACESSO_ANT_TIER, DS_TIER) VALUES ('TIER-APO', 'APOIADOR', 50, 'N', 'Badge digital e acompanhamento publico da missao')
  INTO TB_TIER (ID_TIER, NM_TIER, VL_MIN_TIER, FL_ACESSO_ANT_TIER, DS_TIER) VALUES ('TIER-OPR', 'OPERATIVO', 150, 'S', 'Acesso antecipado aos boletins tecnicos')
  INTO TB_TIER (ID_TIER, NM_TIER, VL_MIN_TIER, FL_ACESSO_ANT_TIER, DS_TIER) VALUES ('TIER-CMD', 'COMANDANTE', 500, 'S', 'Nome gravado no hangar digital da nave')
SELECT 1 FROM DUAL;

INSERT ALL
  INTO TB_USUARIO (ID_USUARIO, NM_USUARIO, EM_USUARIO, SEN_HASH_USUARIO, STT_USUARIO, RL_USUARIO, DT_CADST_USUARIO) VALUES ('USR-001','Ana Ribeiro','ana.ribeiro@example.com','hash_usr_001','ATIVO','ADMIN',DATE '2025-01-10')
  INTO TB_USUARIO (ID_USUARIO, NM_USUARIO, EM_USUARIO, SEN_HASH_USUARIO, STT_USUARIO, RL_USUARIO, DT_CADST_USUARIO) VALUES ('USR-002','Bruno Castro','bruno.castro@example.com','hash_usr_002','ATIVO','USER',DATE '2025-01-12')
  INTO TB_USUARIO (ID_USUARIO, NM_USUARIO, EM_USUARIO, SEN_HASH_USUARIO, STT_USUARIO, RL_USUARIO, DT_CADST_USUARIO) VALUES ('USR-003','Carla Nunes','carla.nunes@example.com','hash_usr_003','ATIVO','USER',DATE '2025-01-15')
  INTO TB_USUARIO (ID_USUARIO, NM_USUARIO, EM_USUARIO, SEN_HASH_USUARIO, STT_USUARIO, RL_USUARIO, DT_CADST_USUARIO) VALUES ('USR-004','Diego Martins','diego.martins@example.com','hash_usr_004','ATIVO','USER',DATE '2025-01-18')
  INTO TB_USUARIO (ID_USUARIO, NM_USUARIO, EM_USUARIO, SEN_HASH_USUARIO, STT_USUARIO, RL_USUARIO, DT_CADST_USUARIO) VALUES ('USR-005','Elisa Rocha','elisa.rocha@example.com','hash_usr_005','ATIVO','USER',DATE '2025-01-21')
  INTO TB_USUARIO (ID_USUARIO, NM_USUARIO, EM_USUARIO, SEN_HASH_USUARIO, STT_USUARIO, RL_USUARIO, DT_CADST_USUARIO) VALUES ('USR-006','Felipe Lima','felipe.lima@example.com','hash_usr_006','ATIVO','USER',DATE '2025-01-25')
  INTO TB_USUARIO (ID_USUARIO, NM_USUARIO, EM_USUARIO, SEN_HASH_USUARIO, STT_USUARIO, RL_USUARIO, DT_CADST_USUARIO) VALUES ('USR-007','Gabriela Torres','gabriela.torres@example.com','hash_usr_007','ATIVO','USER',DATE '2025-02-02')
  INTO TB_USUARIO (ID_USUARIO, NM_USUARIO, EM_USUARIO, SEN_HASH_USUARIO, STT_USUARIO, RL_USUARIO, DT_CADST_USUARIO) VALUES ('USR-008','Henrique Alves','henrique.alves@example.com','hash_usr_008','ATIVO','USER',DATE '2025-02-05')
  INTO TB_USUARIO (ID_USUARIO, NM_USUARIO, EM_USUARIO, SEN_HASH_USUARIO, STT_USUARIO, RL_USUARIO, DT_CADST_USUARIO) VALUES ('USR-009','Isabela Freitas','isabela.freitas@example.com','hash_usr_009','ATIVO','USER',DATE '2025-02-07')
  INTO TB_USUARIO (ID_USUARIO, NM_USUARIO, EM_USUARIO, SEN_HASH_USUARIO, STT_USUARIO, RL_USUARIO, DT_CADST_USUARIO) VALUES ('USR-010','Joao Pereira','joao.pereira@example.com','hash_usr_010','ATIVO','ADMIN',DATE '2025-02-10')
  INTO TB_USUARIO (ID_USUARIO, NM_USUARIO, EM_USUARIO, SEN_HASH_USUARIO, STT_USUARIO, RL_USUARIO, DT_CADST_USUARIO) VALUES ('USR-011','Karen Souza','karen.souza@example.com','hash_usr_011','ATIVO','USER',DATE '2025-02-13')
  INTO TB_USUARIO (ID_USUARIO, NM_USUARIO, EM_USUARIO, SEN_HASH_USUARIO, STT_USUARIO, RL_USUARIO, DT_CADST_USUARIO) VALUES ('USR-012','Lucas Mendes','lucas.mendes@example.com','hash_usr_012','ATIVO','USER',DATE '2025-02-16')
  INTO TB_USUARIO (ID_USUARIO, NM_USUARIO, EM_USUARIO, SEN_HASH_USUARIO, STT_USUARIO, RL_USUARIO, DT_CADST_USUARIO) VALUES ('USR-013','Marina Costa','marina.costa@example.com','hash_usr_013','ATIVO','USER',DATE '2025-02-18')
  INTO TB_USUARIO (ID_USUARIO, NM_USUARIO, EM_USUARIO, SEN_HASH_USUARIO, STT_USUARIO, RL_USUARIO, DT_CADST_USUARIO) VALUES ('USR-014','Nicolas Barros','nicolas.barros@example.com','hash_usr_014','ATIVO','USER',DATE '2025-02-20')
  INTO TB_USUARIO (ID_USUARIO, NM_USUARIO, EM_USUARIO, SEN_HASH_USUARIO, STT_USUARIO, RL_USUARIO, DT_CADST_USUARIO) VALUES ('USR-015','Olivia Santos','olivia.santos@example.com','hash_usr_015','ATIVO','USER',DATE '2025-02-24')
  INTO TB_USUARIO (ID_USUARIO, NM_USUARIO, EM_USUARIO, SEN_HASH_USUARIO, STT_USUARIO, RL_USUARIO, DT_CADST_USUARIO) VALUES ('USR-016','Paulo Teixeira','paulo.teixeira@example.com','hash_usr_016','ATIVO','USER',DATE '2025-03-01')
  INTO TB_USUARIO (ID_USUARIO, NM_USUARIO, EM_USUARIO, SEN_HASH_USUARIO, STT_USUARIO, RL_USUARIO, DT_CADST_USUARIO) VALUES ('USR-017','Renata Gomes','renata.gomes@example.com','hash_usr_017','ATIVO','USER',DATE '2025-03-04')
  INTO TB_USUARIO (ID_USUARIO, NM_USUARIO, EM_USUARIO, SEN_HASH_USUARIO, STT_USUARIO, RL_USUARIO, DT_CADST_USUARIO) VALUES ('USR-018','Samuel Dias','samuel.dias@example.com','hash_usr_018','ATIVO','USER',DATE '2025-03-07')
  INTO TB_USUARIO (ID_USUARIO, NM_USUARIO, EM_USUARIO, SEN_HASH_USUARIO, STT_USUARIO, RL_USUARIO, DT_CADST_USUARIO) VALUES ('USR-019','Tatiana Campos','tatiana.campos@example.com','hash_usr_019','ATIVO','USER',DATE '2025-03-11')
  INTO TB_USUARIO (ID_USUARIO, NM_USUARIO, EM_USUARIO, SEN_HASH_USUARIO, STT_USUARIO, RL_USUARIO, DT_CADST_USUARIO) VALUES ('USR-020','Victor Araujo','victor.araujo@example.com','hash_usr_020','ATIVO','ADMIN',DATE '2025-03-15')
  INTO TB_USUARIO (ID_USUARIO, NM_USUARIO, EM_USUARIO, SEN_HASH_USUARIO, STT_USUARIO, RL_USUARIO, DT_CADST_USUARIO) VALUES ('USR-021','Lia Carvalho','lia.carvalho@example.com','hash_usr_021','INATIVO','USER',DATE '2024-09-10')
  INTO TB_USUARIO (ID_USUARIO, NM_USUARIO, EM_USUARIO, SEN_HASH_USUARIO, STT_USUARIO, RL_USUARIO, DT_CADST_USUARIO) VALUES ('USR-022','Mateus Farias','mateus.farias@example.com','hash_usr_022','ATIVO','USER',DATE '2025-03-18')
  INTO TB_USUARIO (ID_USUARIO, NM_USUARIO, EM_USUARIO, SEN_HASH_USUARIO, STT_USUARIO, RL_USUARIO, DT_CADST_USUARIO) VALUES ('USR-023','Bianca Mota','bianca.mota@example.com','hash_usr_023','ATIVO','USER',DATE '2025-03-22')
  INTO TB_USUARIO (ID_USUARIO, NM_USUARIO, EM_USUARIO, SEN_HASH_USUARIO, STT_USUARIO, RL_USUARIO, DT_CADST_USUARIO) VALUES ('USR-024','Cesar Prado','cesar.prado@example.com','hash_usr_024','ATIVO','USER',DATE '2025-03-26')
  INTO TB_USUARIO (ID_USUARIO, NM_USUARIO, EM_USUARIO, SEN_HASH_USUARIO, STT_USUARIO, RL_USUARIO, DT_CADST_USUARIO) VALUES ('USR-025','Daniela Pires','daniela.pires@example.com','hash_usr_025','ATIVO','USER',DATE '2025-03-29')
  INTO TB_USUARIO (ID_USUARIO, NM_USUARIO, EM_USUARIO, SEN_HASH_USUARIO, STT_USUARIO, RL_USUARIO, DT_CADST_USUARIO) VALUES ('USR-026','Eduardo Reis','eduardo.reis@example.com','hash_usr_026','ATIVO','USER',DATE '2025-04-02')
  INTO TB_USUARIO (ID_USUARIO, NM_USUARIO, EM_USUARIO, SEN_HASH_USUARIO, STT_USUARIO, RL_USUARIO, DT_CADST_USUARIO) VALUES ('USR-027','Fernanda Maia','fernanda.maia@example.com','hash_usr_027','ATIVO','USER',DATE '2025-04-05')
  INTO TB_USUARIO (ID_USUARIO, NM_USUARIO, EM_USUARIO, SEN_HASH_USUARIO, STT_USUARIO, RL_USUARIO, DT_CADST_USUARIO) VALUES ('USR-028','Gustavo Neri','gustavo.neri@example.com','hash_usr_028','ATIVO','USER',DATE '2025-04-08')
  INTO TB_USUARIO (ID_USUARIO, NM_USUARIO, EM_USUARIO, SEN_HASH_USUARIO, STT_USUARIO, RL_USUARIO, DT_CADST_USUARIO) VALUES ('USR-029','Helena Brito','helena.brito@example.com','hash_usr_029','ATIVO','USER',DATE '2025-04-11')
  INTO TB_USUARIO (ID_USUARIO, NM_USUARIO, EM_USUARIO, SEN_HASH_USUARIO, STT_USUARIO, RL_USUARIO, DT_CADST_USUARIO) VALUES ('USR-030','Igor Sales','igor.sales@example.com','hash_usr_030','ATIVO','USER',DATE '2025-04-15')
SELECT 1 FROM DUAL;

INSERT ALL
  INTO TB_MISSAO (ID_MISSAO, CD_MISSAO, NM_MISSAO, DS_MISSAO, STT_MISSAO, VL_META_MISSAO, DT_LIMITE, TP_ORB_MISSAO, VD_UTIL_MISSAO, CG_UTIL_MISSAO, COORD_LAT_MISSAO, COORD_LNG_MISSAO, BADG_MISSAO, TB_ORGANIZACAO_ID_ORGANIZACAO, TB_AGENCIA_ID_AGENCIA) VALUES ('MIS-001','AMZ-01','Sentinela Amazonia','Monitoramento de focos de calor e desmatamento.','ATIVA',120000,DATE '2026-12-31','SSO','3 ANOS','CAMERA MULTIESPECTRAL',-3.465305,-62.215881,'Guardiao Verde','ORG-002','AGE-001')
  INTO TB_MISSAO (ID_MISSAO, CD_MISSAO, NM_MISSAO, DS_MISSAO, STT_MISSAO, VL_META_MISSAO, DT_LIMITE, TP_ORB_MISSAO, VD_UTIL_MISSAO, CG_UTIL_MISSAO, COORD_LAT_MISSAO, COORD_LNG_MISSAO, BADG_MISSAO, TB_ORGANIZACAO_ID_ORGANIZACAO, TB_AGENCIA_ID_AGENCIA) VALUES ('MIS-002','ATL-02','Azul Profundo','Observacao costeira e qualidade da agua.','ATIVA',90000,DATE '2026-10-15','LEO','2 ANOS','SENSOR HIPERESPECTRAL',-23.960833,-46.333889,'Mar Vivo','ORG-003','AGE-004')
  INTO TB_MISSAO (ID_MISSAO, CD_MISSAO, NM_MISSAO, DS_MISSAO, STT_MISSAO, VL_META_MISSAO, DT_LIMITE, TP_ORB_MISSAO, VD_UTIL_MISSAO, CG_UTIL_MISSAO, COORD_LAT_MISSAO, COORD_LNG_MISSAO, BADG_MISSAO, TB_ORGANIZACAO_ID_ORGANIZACAO, TB_AGENCIA_ID_AGENCIA) VALUES ('MIS-003','AGR-03','Safra Orbital','Apoio a agricultura de precisao.','ATIVA',150000,DATE '2027-02-28','SSO','4 ANOS','RADAR SAR',-15.780100,-47.929200,'Campo Inteligente','ORG-004','AGE-001')
  INTO TB_MISSAO (ID_MISSAO, CD_MISSAO, NM_MISSAO, DS_MISSAO, STT_MISSAO, VL_META_MISSAO, DT_LIMITE, TP_ORB_MISSAO, VD_UTIL_MISSAO, CG_UTIL_MISSAO, COORD_LAT_MISSAO, COORD_LNG_MISSAO, BADG_MISSAO, TB_ORGANIZACAO_ID_ORGANIZACAO, TB_AGENCIA_ID_AGENCIA) VALUES ('MIS-004','CLM-04','Chuva Certa','Dados para defesa civil em eventos extremos.','CRIACAO',80000,DATE '2026-09-30','LEO','2 ANOS','RADIOMETRO',-22.906847,-43.172897,'Alerta Rapido','ORG-005','AGE-002')
  INTO TB_MISSAO (ID_MISSAO, CD_MISSAO, NM_MISSAO, DS_MISSAO, STT_MISSAO, VL_META_MISSAO, DT_LIMITE, TP_ORB_MISSAO, VD_UTIL_MISSAO, CG_UTIL_MISSAO, COORD_LAT_MISSAO, COORD_LNG_MISSAO, BADG_MISSAO, TB_ORGANIZACAO_ID_ORGANIZACAO, TB_AGENCIA_ID_AGENCIA) VALUES ('MIS-005','LUN-05','Ponte Lunar','Teste de comunicacao terra-lua.','CRIACAO',250000,DATE '2027-06-30','MEO','5 ANOS','REPETIDOR OPTICO',0,0,'Lunar Pioneer','ORG-001','AGE-003')
  INTO TB_MISSAO (ID_MISSAO, CD_MISSAO, NM_MISSAO, DS_MISSAO, STT_MISSAO, VL_META_MISSAO, DT_LIMITE, TP_ORB_MISSAO, VD_UTIL_MISSAO, CG_UTIL_MISSAO, COORD_LAT_MISSAO, COORD_LNG_MISSAO, BADG_MISSAO, TB_ORGANIZACAO_ID_ORGANIZACAO, TB_AGENCIA_ID_AGENCIA) VALUES ('MIS-006','SOL-06','Helios Clima','Coleta de dados solares para clima espacial.','ATIVA',180000,DATE '2027-03-31','HEO','3 ANOS','MAGNETOMETRO',-10.947247,-37.073082,'Vento Solar','ORG-001','AGE-005')
  INTO TB_MISSAO (ID_MISSAO, CD_MISSAO, NM_MISSAO, DS_MISSAO, STT_MISSAO, VL_META_MISSAO, DT_LIMITE, TP_ORB_MISSAO, VD_UTIL_MISSAO, CG_UTIL_MISSAO, COORD_LAT_MISSAO, COORD_LNG_MISSAO, BADG_MISSAO, TB_ORGANIZACAO_ID_ORGANIZACAO, TB_AGENCIA_ID_AGENCIA) VALUES ('MIS-007','AND-07','Cordilheira Viva','Monitoramento de geleiras andinas.','CONCLUIDA',110000,DATE '2025-12-20','SSO','3 ANOS','CAMERA TERMAL',-13.163141,-72.544963,'Gelo Vivo','ORG-005','AGE-002')
  INTO TB_MISSAO (ID_MISSAO, CD_MISSAO, NM_MISSAO, DS_MISSAO, STT_MISSAO, VL_META_MISSAO, DT_LIMITE, TP_ORB_MISSAO, VD_UTIL_MISSAO, CG_UTIL_MISSAO, COORD_LAT_MISSAO, COORD_LNG_MISSAO, BADG_MISSAO, TB_ORGANIZACAO_ID_ORGANIZACAO, TB_AGENCIA_ID_AGENCIA) VALUES ('MIS-008','PAN-08','Pantanal Alerta','Deteccao precoce de queimadas no Pantanal.','ATIVA',100000,DATE '2026-11-10','LEO','3 ANOS','CAMERA INFRAVERMELHA',-19.005000,-57.650000,'Pantanal Guard','ORG-002','AGE-001')
  INTO TB_MISSAO (ID_MISSAO, CD_MISSAO, NM_MISSAO, DS_MISSAO, STT_MISSAO, VL_META_MISSAO, DT_LIMITE, TP_ORB_MISSAO, VD_UTIL_MISSAO, CG_UTIL_MISSAO, COORD_LAT_MISSAO, COORD_LNG_MISSAO, BADG_MISSAO, TB_ORGANIZACAO_ID_ORGANIZACAO, TB_AGENCIA_ID_AGENCIA) VALUES ('MIS-009','URB-09','Cidades Resilientes','Analise urbana para ilhas de calor.','ATIVA',95000,DATE '2026-08-15','SSO','2 ANOS','CAMERA RGB',-23.550520,-46.633308,'Cidade Fria','ORG-005','AGE-004')
  INTO TB_MISSAO (ID_MISSAO, CD_MISSAO, NM_MISSAO, DS_MISSAO, STT_MISSAO, VL_META_MISSAO, DT_LIMITE, TP_ORB_MISSAO, VD_UTIL_MISSAO, CG_UTIL_MISSAO, COORD_LAT_MISSAO, COORD_LNG_MISSAO, BADG_MISSAO, TB_ORGANIZACAO_ID_ORGANIZACAO, TB_AGENCIA_ID_AGENCIA) VALUES ('MIS-010','BIO-10','Biomas Conectados','Integracao de indicadores ambientais nacionais.','FALHOU',130000,DATE '2025-08-30','LEO','3 ANOS','SENSOR AMBIENTAL',-12.970400,-38.512400,'Rede Bio','ORG-002','AGE-005')
SELECT 1 FROM DUAL;

INSERT ALL
  INTO TB_NAVE (ID_NAVE, NM_NAVE, CLS_NAVE, IMG_URL_NAVE, TB_MISSAO_ID_MISSAO) VALUES ('NAV-001','Sabia-X','OBSERVACAO LEVE','https://img.starforge.local/sabia-x.png','MIS-001')
  INTO TB_NAVE (ID_NAVE, NM_NAVE, CLS_NAVE, IMG_URL_NAVE, TB_MISSAO_ID_MISSAO) VALUES ('NAV-002','Tucano Prime','OBSERVACAO MEDIA','https://img.starforge.local/tucano-prime.png','MIS-002')
  INTO TB_NAVE (ID_NAVE, NM_NAVE, CLS_NAVE, IMG_URL_NAVE, TB_MISSAO_ID_MISSAO) VALUES ('NAV-003','Arara SAR','RADAR PESADO','https://img.starforge.local/arara-sar.png','MIS-003')
  INTO TB_NAVE (ID_NAVE, NM_NAVE, CLS_NAVE, IMG_URL_NAVE, TB_MISSAO_ID_MISSAO) VALUES ('NAV-004','Nimbus-1','METEOROLOGICA','https://img.starforge.local/nimbus-1.png','MIS-004')
  INTO TB_NAVE (ID_NAVE, NM_NAVE, CLS_NAVE, IMG_URL_NAVE, TB_MISSAO_ID_MISSAO) VALUES ('NAV-005','LuaLink','COMUNICACAO','https://img.starforge.local/lualink.png','MIS-005')
  INTO TB_NAVE (ID_NAVE, NM_NAVE, CLS_NAVE, IMG_URL_NAVE, TB_MISSAO_ID_MISSAO) VALUES ('NAV-006','Helios Scout','CIENCIA SOLAR','https://img.starforge.local/helios-scout.png','MIS-006')
  INTO TB_NAVE (ID_NAVE, NM_NAVE, CLS_NAVE, IMG_URL_NAVE, TB_MISSAO_ID_MISSAO) VALUES ('NAV-007','Condor Ice','OBSERVACAO TERMAL','https://img.starforge.local/condor-ice.png','MIS-007')
  INTO TB_NAVE (ID_NAVE, NM_NAVE, CLS_NAVE, IMG_URL_NAVE, TB_MISSAO_ID_MISSAO) VALUES ('NAV-008','Jabiru Fire','INFRAVERMELHA','https://img.starforge.local/jabiru-fire.png','MIS-008')
  INTO TB_NAVE (ID_NAVE, NM_NAVE, CLS_NAVE, IMG_URL_NAVE, TB_MISSAO_ID_MISSAO) VALUES ('NAV-009','Iris Urbana','OBSERVACAO URBANA','https://img.starforge.local/iris-urbana.png','MIS-009')
  INTO TB_NAVE (ID_NAVE, NM_NAVE, CLS_NAVE, IMG_URL_NAVE, TB_MISSAO_ID_MISSAO) VALUES ('NAV-010','BioNet One','AMBIENTAL','https://img.starforge.local/bionet-one.png','MIS-010')
SELECT 1 FROM DUAL;

INSERT ALL
  INTO TB_FASE_MISSAO (ID_FASE_MISSAO, NMR_FASE_MISSAO, NM_FASE_MISSAO, DS_FASE_MISSAO, STT_FASE, PCT_FASE_MISSAO, TB_MISSAO_ID_MISSAO) VALUES ('FAS-001-1',1,'Projeto orbital','Definicao de requisitos e orbita.','CONCLUIDO',100,'MIS-001')
  INTO TB_FASE_MISSAO (ID_FASE_MISSAO, NMR_FASE_MISSAO, NM_FASE_MISSAO, DS_FASE_MISSAO, STT_FASE, PCT_FASE_MISSAO, TB_MISSAO_ID_MISSAO) VALUES ('FAS-001-2',2,'Integracao do payload','Montagem da carga util.','EM ANDAMENTO',65,'MIS-001')
  INTO TB_FASE_MISSAO (ID_FASE_MISSAO, NMR_FASE_MISSAO, NM_FASE_MISSAO, DS_FASE_MISSAO, STT_FASE, PCT_FASE_MISSAO, TB_MISSAO_ID_MISSAO) VALUES ('FAS-001-3',3,'Testes ambientais','Vibracao e termovacuo.','AGUARDANDO',0,'MIS-001')
  INTO TB_FASE_MISSAO (ID_FASE_MISSAO, NMR_FASE_MISSAO, NM_FASE_MISSAO, DS_FASE_MISSAO, STT_FASE, PCT_FASE_MISSAO, TB_MISSAO_ID_MISSAO) VALUES ('FAS-001-4',4,'Lancamento','Janela final de lancamento.','AGUARDANDO',0,'MIS-001')
  INTO TB_FASE_MISSAO (ID_FASE_MISSAO, NMR_FASE_MISSAO, NM_FASE_MISSAO, DS_FASE_MISSAO, STT_FASE, PCT_FASE_MISSAO, TB_MISSAO_ID_MISSAO) VALUES ('FAS-002-1',1,'Projeto orbital','Definicao costeira.','CONCLUIDO',100,'MIS-002')
  INTO TB_FASE_MISSAO (ID_FASE_MISSAO, NMR_FASE_MISSAO, NM_FASE_MISSAO, DS_FASE_MISSAO, STT_FASE, PCT_FASE_MISSAO, TB_MISSAO_ID_MISSAO) VALUES ('FAS-002-2',2,'Integracao do payload','Calibracao hiper espectral.','EM ANDAMENTO',40,'MIS-002')
  INTO TB_FASE_MISSAO (ID_FASE_MISSAO, NMR_FASE_MISSAO, NM_FASE_MISSAO, DS_FASE_MISSAO, STT_FASE, PCT_FASE_MISSAO, TB_MISSAO_ID_MISSAO) VALUES ('FAS-002-3',3,'Testes ambientais','Ensaios de bancada.','AGUARDANDO',0,'MIS-002')
  INTO TB_FASE_MISSAO (ID_FASE_MISSAO, NMR_FASE_MISSAO, NM_FASE_MISSAO, DS_FASE_MISSAO, STT_FASE, PCT_FASE_MISSAO, TB_MISSAO_ID_MISSAO) VALUES ('FAS-002-4',4,'Lancamento','Campanha de lancamento.','AGUARDANDO',0,'MIS-002')
  INTO TB_FASE_MISSAO (ID_FASE_MISSAO, NMR_FASE_MISSAO, NM_FASE_MISSAO, DS_FASE_MISSAO, STT_FASE, PCT_FASE_MISSAO, TB_MISSAO_ID_MISSAO) VALUES ('FAS-003-1',1,'Projeto orbital','Planejamento SAR.','CONCLUIDO',100,'MIS-003')
  INTO TB_FASE_MISSAO (ID_FASE_MISSAO, NMR_FASE_MISSAO, NM_FASE_MISSAO, DS_FASE_MISSAO, STT_FASE, PCT_FASE_MISSAO, TB_MISSAO_ID_MISSAO) VALUES ('FAS-003-2',2,'Integracao do payload','Antena e radar.','EM ANDAMENTO',55,'MIS-003')
  INTO TB_FASE_MISSAO (ID_FASE_MISSAO, NMR_FASE_MISSAO, NM_FASE_MISSAO, DS_FASE_MISSAO, STT_FASE, PCT_FASE_MISSAO, TB_MISSAO_ID_MISSAO) VALUES ('FAS-003-3',3,'Testes ambientais','Qualificacao estrutural.','AGUARDANDO',0,'MIS-003')
  INTO TB_FASE_MISSAO (ID_FASE_MISSAO, NMR_FASE_MISSAO, NM_FASE_MISSAO, DS_FASE_MISSAO, STT_FASE, PCT_FASE_MISSAO, TB_MISSAO_ID_MISSAO) VALUES ('FAS-003-4',4,'Lancamento','Operacao final.','AGUARDANDO',0,'MIS-003')
  INTO TB_FASE_MISSAO (ID_FASE_MISSAO, NMR_FASE_MISSAO, NM_FASE_MISSAO, DS_FASE_MISSAO, STT_FASE, PCT_FASE_MISSAO, TB_MISSAO_ID_MISSAO) VALUES ('FAS-004-1',1,'Projeto orbital','Modelo de cobertura.','EM ANDAMENTO',25,'MIS-004')
  INTO TB_FASE_MISSAO (ID_FASE_MISSAO, NMR_FASE_MISSAO, NM_FASE_MISSAO, DS_FASE_MISSAO, STT_FASE, PCT_FASE_MISSAO, TB_MISSAO_ID_MISSAO) VALUES ('FAS-004-2',2,'Integracao do payload','Radiometro em compra.','AGUARDANDO',0,'MIS-004')
  INTO TB_FASE_MISSAO (ID_FASE_MISSAO, NMR_FASE_MISSAO, NM_FASE_MISSAO, DS_FASE_MISSAO, STT_FASE, PCT_FASE_MISSAO, TB_MISSAO_ID_MISSAO) VALUES ('FAS-004-3',3,'Testes ambientais','Aguardando hardware.','AGUARDANDO',0,'MIS-004')
  INTO TB_FASE_MISSAO (ID_FASE_MISSAO, NMR_FASE_MISSAO, NM_FASE_MISSAO, DS_FASE_MISSAO, STT_FASE, PCT_FASE_MISSAO, TB_MISSAO_ID_MISSAO) VALUES ('FAS-004-4',4,'Lancamento','Nao agendado.','AGUARDANDO',0,'MIS-004')
  INTO TB_FASE_MISSAO (ID_FASE_MISSAO, NMR_FASE_MISSAO, NM_FASE_MISSAO, DS_FASE_MISSAO, STT_FASE, PCT_FASE_MISSAO, TB_MISSAO_ID_MISSAO) VALUES ('FAS-005-1',1,'Projeto orbital','Estudo translunar.','EM ANDAMENTO',15,'MIS-005')
  INTO TB_FASE_MISSAO (ID_FASE_MISSAO, NMR_FASE_MISSAO, NM_FASE_MISSAO, DS_FASE_MISSAO, STT_FASE, PCT_FASE_MISSAO, TB_MISSAO_ID_MISSAO) VALUES ('FAS-005-2',2,'Integracao do payload','Aguardando arquitetura.','AGUARDANDO',0,'MIS-005')
  INTO TB_FASE_MISSAO (ID_FASE_MISSAO, NMR_FASE_MISSAO, NM_FASE_MISSAO, DS_FASE_MISSAO, STT_FASE, PCT_FASE_MISSAO, TB_MISSAO_ID_MISSAO) VALUES ('FAS-005-3',3,'Testes ambientais','Nao iniciado.','AGUARDANDO',0,'MIS-005')
  INTO TB_FASE_MISSAO (ID_FASE_MISSAO, NMR_FASE_MISSAO, NM_FASE_MISSAO, DS_FASE_MISSAO, STT_FASE, PCT_FASE_MISSAO, TB_MISSAO_ID_MISSAO) VALUES ('FAS-005-4',4,'Lancamento','Nao agendado.','AGUARDANDO',0,'MIS-005')
  INTO TB_FASE_MISSAO (ID_FASE_MISSAO, NMR_FASE_MISSAO, NM_FASE_MISSAO, DS_FASE_MISSAO, STT_FASE, PCT_FASE_MISSAO, TB_MISSAO_ID_MISSAO) VALUES ('FAS-006-1',1,'Projeto orbital','Trajetoria heliocentrica.','CONCLUIDO',100,'MIS-006')
  INTO TB_FASE_MISSAO (ID_FASE_MISSAO, NMR_FASE_MISSAO, NM_FASE_MISSAO, DS_FASE_MISSAO, STT_FASE, PCT_FASE_MISSAO, TB_MISSAO_ID_MISSAO) VALUES ('FAS-006-2',2,'Integracao do payload','Magnetometro em integracao.','EM ANDAMENTO',70,'MIS-006')
  INTO TB_FASE_MISSAO (ID_FASE_MISSAO, NMR_FASE_MISSAO, NM_FASE_MISSAO, DS_FASE_MISSAO, STT_FASE, PCT_FASE_MISSAO, TB_MISSAO_ID_MISSAO) VALUES ('FAS-006-3',3,'Testes ambientais','Aguardando janela.','AGUARDANDO',0,'MIS-006')
  INTO TB_FASE_MISSAO (ID_FASE_MISSAO, NMR_FASE_MISSAO, NM_FASE_MISSAO, DS_FASE_MISSAO, STT_FASE, PCT_FASE_MISSAO, TB_MISSAO_ID_MISSAO) VALUES ('FAS-006-4',4,'Lancamento','Campanha futura.','AGUARDANDO',0,'MIS-006')
  INTO TB_FASE_MISSAO (ID_FASE_MISSAO, NMR_FASE_MISSAO, NM_FASE_MISSAO, DS_FASE_MISSAO, STT_FASE, PCT_FASE_MISSAO, TB_MISSAO_ID_MISSAO) VALUES ('FAS-007-1',1,'Projeto orbital','Projeto concluido.','CONCLUIDO',100,'MIS-007')
  INTO TB_FASE_MISSAO (ID_FASE_MISSAO, NMR_FASE_MISSAO, NM_FASE_MISSAO, DS_FASE_MISSAO, STT_FASE, PCT_FASE_MISSAO, TB_MISSAO_ID_MISSAO) VALUES ('FAS-007-2',2,'Integracao do payload','Payload concluido.','CONCLUIDO',100,'MIS-007')
  INTO TB_FASE_MISSAO (ID_FASE_MISSAO, NMR_FASE_MISSAO, NM_FASE_MISSAO, DS_FASE_MISSAO, STT_FASE, PCT_FASE_MISSAO, TB_MISSAO_ID_MISSAO) VALUES ('FAS-007-3',3,'Testes ambientais','Testes concluidos.','CONCLUIDO',100,'MIS-007')
  INTO TB_FASE_MISSAO (ID_FASE_MISSAO, NMR_FASE_MISSAO, NM_FASE_MISSAO, DS_FASE_MISSAO, STT_FASE, PCT_FASE_MISSAO, TB_MISSAO_ID_MISSAO) VALUES ('FAS-007-4',4,'Lancamento','Lancamento concluido.','CONCLUIDO',100,'MIS-007')
  INTO TB_FASE_MISSAO (ID_FASE_MISSAO, NMR_FASE_MISSAO, NM_FASE_MISSAO, DS_FASE_MISSAO, STT_FASE, PCT_FASE_MISSAO, TB_MISSAO_ID_MISSAO) VALUES ('FAS-008-1',1,'Projeto orbital','Cobertura Pantanal.','CONCLUIDO',100,'MIS-008')
  INTO TB_FASE_MISSAO (ID_FASE_MISSAO, NMR_FASE_MISSAO, NM_FASE_MISSAO, DS_FASE_MISSAO, STT_FASE, PCT_FASE_MISSAO, TB_MISSAO_ID_MISSAO) VALUES ('FAS-008-2',2,'Integracao do payload','Camera IR.','EM ANDAMENTO',35,'MIS-008')
  INTO TB_FASE_MISSAO (ID_FASE_MISSAO, NMR_FASE_MISSAO, NM_FASE_MISSAO, DS_FASE_MISSAO, STT_FASE, PCT_FASE_MISSAO, TB_MISSAO_ID_MISSAO) VALUES ('FAS-008-3',3,'Testes ambientais','Aguardando amostras.','AGUARDANDO',0,'MIS-008')
  INTO TB_FASE_MISSAO (ID_FASE_MISSAO, NMR_FASE_MISSAO, NM_FASE_MISSAO, DS_FASE_MISSAO, STT_FASE, PCT_FASE_MISSAO, TB_MISSAO_ID_MISSAO) VALUES ('FAS-008-4',4,'Lancamento','Sem janela.','AGUARDANDO',0,'MIS-008')
  INTO TB_FASE_MISSAO (ID_FASE_MISSAO, NMR_FASE_MISSAO, NM_FASE_MISSAO, DS_FASE_MISSAO, STT_FASE, PCT_FASE_MISSAO, TB_MISSAO_ID_MISSAO) VALUES ('FAS-009-1',1,'Projeto orbital','Passagens urbanas.','CONCLUIDO',100,'MIS-009')
  INTO TB_FASE_MISSAO (ID_FASE_MISSAO, NMR_FASE_MISSAO, NM_FASE_MISSAO, DS_FASE_MISSAO, STT_FASE, PCT_FASE_MISSAO, TB_MISSAO_ID_MISSAO) VALUES ('FAS-009-2',2,'Integracao do payload','Camera RGB.','EM ANDAMENTO',20,'MIS-009')
  INTO TB_FASE_MISSAO (ID_FASE_MISSAO, NMR_FASE_MISSAO, NM_FASE_MISSAO, DS_FASE_MISSAO, STT_FASE, PCT_FASE_MISSAO, TB_MISSAO_ID_MISSAO) VALUES ('FAS-009-3',3,'Testes ambientais','Fila de teste.','AGUARDANDO',0,'MIS-009')
  INTO TB_FASE_MISSAO (ID_FASE_MISSAO, NMR_FASE_MISSAO, NM_FASE_MISSAO, DS_FASE_MISSAO, STT_FASE, PCT_FASE_MISSAO, TB_MISSAO_ID_MISSAO) VALUES ('FAS-009-4',4,'Lancamento','Sem janela.','AGUARDANDO',0,'MIS-009')
  INTO TB_FASE_MISSAO (ID_FASE_MISSAO, NMR_FASE_MISSAO, NM_FASE_MISSAO, DS_FASE_MISSAO, STT_FASE, PCT_FASE_MISSAO, TB_MISSAO_ID_MISSAO) VALUES ('FAS-010-1',1,'Projeto orbital','Projeto cancelado.','CONCLUIDO',100,'MIS-010')
  INTO TB_FASE_MISSAO (ID_FASE_MISSAO, NMR_FASE_MISSAO, NM_FASE_MISSAO, DS_FASE_MISSAO, STT_FASE, PCT_FASE_MISSAO, TB_MISSAO_ID_MISSAO) VALUES ('FAS-010-2',2,'Integracao do payload','Falha de fornecimento.','CONCLUIDO',100,'MIS-010')
  INTO TB_FASE_MISSAO (ID_FASE_MISSAO, NMR_FASE_MISSAO, NM_FASE_MISSAO, DS_FASE_MISSAO, STT_FASE, PCT_FASE_MISSAO, TB_MISSAO_ID_MISSAO) VALUES ('FAS-010-3',3,'Testes ambientais','Teste falhou.','CONCLUIDO',100,'MIS-010')
  INTO TB_FASE_MISSAO (ID_FASE_MISSAO, NMR_FASE_MISSAO, NM_FASE_MISSAO, DS_FASE_MISSAO, STT_FASE, PCT_FASE_MISSAO, TB_MISSAO_ID_MISSAO) VALUES ('FAS-010-4',4,'Lancamento','Lancamento cancelado.','AGUARDANDO',0,'MIS-010')
SELECT 1 FROM DUAL;

INSERT ALL
  INTO TB_CONTRIBUICAO (ID_CONTRIBUICAO, VL_CONTRIBUICAO, STT_CONTRIBUICAO, MTD_PGT_CONTRIBUICAO, DT_CONTRIBUICAO, TB_USUARIO_ID_USUARIO, TB_MISSAO_ID_MISSAO, TB_TIER_ID_TIER) VALUES ('CONTRIB-001',600,'PENDENTE','PIX',DATE '2026-01-05','USR-001','MIS-001','TIER-CMD')
  INTO TB_CONTRIBUICAO (ID_CONTRIBUICAO, VL_CONTRIBUICAO, STT_CONTRIBUICAO, MTD_PGT_CONTRIBUICAO, DT_CONTRIBUICAO, TB_USUARIO_ID_USUARIO, TB_MISSAO_ID_MISSAO, TB_TIER_ID_TIER) VALUES ('CONTRIB-002',150,'CONFIRMADO','CREDITO',DATE '2026-01-07','USR-002','MIS-001','TIER-OPR')
  INTO TB_CONTRIBUICAO (ID_CONTRIBUICAO, VL_CONTRIBUICAO, STT_CONTRIBUICAO, MTD_PGT_CONTRIBUICAO, DT_CONTRIBUICAO, TB_USUARIO_ID_USUARIO, TB_MISSAO_ID_MISSAO, TB_TIER_ID_TIER) VALUES ('CONTRIB-003',75,'CONFIRMADO','PIX',DATE '2026-01-08','USR-003','MIS-001','TIER-APO')
  INTO TB_CONTRIBUICAO (ID_CONTRIBUICAO, VL_CONTRIBUICAO, STT_CONTRIBUICAO, MTD_PGT_CONTRIBUICAO, DT_CONTRIBUICAO, TB_USUARIO_ID_USUARIO, TB_MISSAO_ID_MISSAO, TB_TIER_ID_TIER) VALUES ('CONTRIB-004',500,'CONFIRMADO','DEBITO',DATE '2026-01-10','USR-004','MIS-002','TIER-CMD')
  INTO TB_CONTRIBUICAO (ID_CONTRIBUICAO, VL_CONTRIBUICAO, STT_CONTRIBUICAO, MTD_PGT_CONTRIBUICAO, DT_CONTRIBUICAO, TB_USUARIO_ID_USUARIO, TB_MISSAO_ID_MISSAO, TB_TIER_ID_TIER) VALUES ('CONTRIB-005',200,'PENDENTE','PIX',DATE '2026-01-12','USR-005','MIS-002','TIER-OPR')
  INTO TB_CONTRIBUICAO (ID_CONTRIBUICAO, VL_CONTRIBUICAO, STT_CONTRIBUICAO, MTD_PGT_CONTRIBUICAO, DT_CONTRIBUICAO, TB_USUARIO_ID_USUARIO, TB_MISSAO_ID_MISSAO, TB_TIER_ID_TIER) VALUES ('CONTRIB-006',60,'CONFIRMADO','CREDITO',DATE '2026-01-15','USR-006','MIS-002','TIER-APO')
  INTO TB_CONTRIBUICAO (ID_CONTRIBUICAO, VL_CONTRIBUICAO, STT_CONTRIBUICAO, MTD_PGT_CONTRIBUICAO, DT_CONTRIBUICAO, TB_USUARIO_ID_USUARIO, TB_MISSAO_ID_MISSAO, TB_TIER_ID_TIER) VALUES ('CONTRIB-007',700,'CONFIRMADO','PIX',DATE '2026-01-17','USR-007','MIS-003','TIER-CMD')
  INTO TB_CONTRIBUICAO (ID_CONTRIBUICAO, VL_CONTRIBUICAO, STT_CONTRIBUICAO, MTD_PGT_CONTRIBUICAO, DT_CONTRIBUICAO, TB_USUARIO_ID_USUARIO, TB_MISSAO_ID_MISSAO, TB_TIER_ID_TIER) VALUES ('CONTRIB-008',180,'CONFIRMADO','DEBITO',DATE '2026-01-18','USR-008','MIS-003','TIER-OPR')
  INTO TB_CONTRIBUICAO (ID_CONTRIBUICAO, VL_CONTRIBUICAO, STT_CONTRIBUICAO, MTD_PGT_CONTRIBUICAO, DT_CONTRIBUICAO, TB_USUARIO_ID_USUARIO, TB_MISSAO_ID_MISSAO, TB_TIER_ID_TIER) VALUES ('CONTRIB-009',80,'PENDENTE','PIX',DATE '2026-01-20','USR-009','MIS-003','TIER-APO')
  INTO TB_CONTRIBUICAO (ID_CONTRIBUICAO, VL_CONTRIBUICAO, STT_CONTRIBUICAO, MTD_PGT_CONTRIBUICAO, DT_CONTRIBUICAO, TB_USUARIO_ID_USUARIO, TB_MISSAO_ID_MISSAO, TB_TIER_ID_TIER) VALUES ('CONTRIB-010',520,'CONFIRMADO','CREDITO',DATE '2026-01-22','USR-010','MIS-004','TIER-CMD')
  INTO TB_CONTRIBUICAO (ID_CONTRIBUICAO, VL_CONTRIBUICAO, STT_CONTRIBUICAO, MTD_PGT_CONTRIBUICAO, DT_CONTRIBUICAO, TB_USUARIO_ID_USUARIO, TB_MISSAO_ID_MISSAO, TB_TIER_ID_TIER) VALUES ('CONTRIB-011',160,'CONFIRMADO','PIX',DATE '2026-01-23','USR-011','MIS-004','TIER-OPR')
  INTO TB_CONTRIBUICAO (ID_CONTRIBUICAO, VL_CONTRIBUICAO, STT_CONTRIBUICAO, MTD_PGT_CONTRIBUICAO, DT_CONTRIBUICAO, TB_USUARIO_ID_USUARIO, TB_MISSAO_ID_MISSAO, TB_TIER_ID_TIER) VALUES ('CONTRIB-012',55,'CONFIRMADO','DEBITO',DATE '2026-01-25','USR-012','MIS-004','TIER-APO')
  INTO TB_CONTRIBUICAO (ID_CONTRIBUICAO, VL_CONTRIBUICAO, STT_CONTRIBUICAO, MTD_PGT_CONTRIBUICAO, DT_CONTRIBUICAO, TB_USUARIO_ID_USUARIO, TB_MISSAO_ID_MISSAO, TB_TIER_ID_TIER) VALUES ('CONTRIB-013',1000,'CONFIRMADO','PIX',DATE '2026-02-01','USR-013','MIS-005','TIER-CMD')
  INTO TB_CONTRIBUICAO (ID_CONTRIBUICAO, VL_CONTRIBUICAO, STT_CONTRIBUICAO, MTD_PGT_CONTRIBUICAO, DT_CONTRIBUICAO, TB_USUARIO_ID_USUARIO, TB_MISSAO_ID_MISSAO, TB_TIER_ID_TIER) VALUES ('CONTRIB-014',250,'PENDENTE','CREDITO',DATE '2026-02-02','USR-014','MIS-005','TIER-OPR')
  INTO TB_CONTRIBUICAO (ID_CONTRIBUICAO, VL_CONTRIBUICAO, STT_CONTRIBUICAO, MTD_PGT_CONTRIBUICAO, DT_CONTRIBUICAO, TB_USUARIO_ID_USUARIO, TB_MISSAO_ID_MISSAO, TB_TIER_ID_TIER) VALUES ('CONTRIB-015',90,'CONFIRMADO','PIX',DATE '2026-02-04','USR-015','MIS-005','TIER-APO')
  INTO TB_CONTRIBUICAO (ID_CONTRIBUICAO, VL_CONTRIBUICAO, STT_CONTRIBUICAO, MTD_PGT_CONTRIBUICAO, DT_CONTRIBUICAO, TB_USUARIO_ID_USUARIO, TB_MISSAO_ID_MISSAO, TB_TIER_ID_TIER) VALUES ('CONTRIB-016',650,'CONFIRMADO','DEBITO',DATE '2026-02-06','USR-016','MIS-006','TIER-CMD')
  INTO TB_CONTRIBUICAO (ID_CONTRIBUICAO, VL_CONTRIBUICAO, STT_CONTRIBUICAO, MTD_PGT_CONTRIBUICAO, DT_CONTRIBUICAO, TB_USUARIO_ID_USUARIO, TB_MISSAO_ID_MISSAO, TB_TIER_ID_TIER) VALUES ('CONTRIB-017',180,'CONFIRMADO','PIX',DATE '2026-02-07','USR-017','MIS-006','TIER-OPR')
  INTO TB_CONTRIBUICAO (ID_CONTRIBUICAO, VL_CONTRIBUICAO, STT_CONTRIBUICAO, MTD_PGT_CONTRIBUICAO, DT_CONTRIBUICAO, TB_USUARIO_ID_USUARIO, TB_MISSAO_ID_MISSAO, TB_TIER_ID_TIER) VALUES ('CONTRIB-018',50,'PENDENTE','CREDITO',DATE '2026-02-09','USR-018','MIS-006','TIER-APO')
  INTO TB_CONTRIBUICAO (ID_CONTRIBUICAO, VL_CONTRIBUICAO, STT_CONTRIBUICAO, MTD_PGT_CONTRIBUICAO, DT_CONTRIBUICAO, TB_USUARIO_ID_USUARIO, TB_MISSAO_ID_MISSAO, TB_TIER_ID_TIER) VALUES ('CONTRIB-019',530,'CONFIRMADO','PIX',DATE '2025-07-01','USR-019','MIS-007','TIER-CMD')
  INTO TB_CONTRIBUICAO (ID_CONTRIBUICAO, VL_CONTRIBUICAO, STT_CONTRIBUICAO, MTD_PGT_CONTRIBUICAO, DT_CONTRIBUICAO, TB_USUARIO_ID_USUARIO, TB_MISSAO_ID_MISSAO, TB_TIER_ID_TIER) VALUES ('CONTRIB-020',170,'CONFIRMADO','DEBITO',DATE '2025-07-02','USR-020','MIS-007','TIER-OPR')
  INTO TB_CONTRIBUICAO (ID_CONTRIBUICAO, VL_CONTRIBUICAO, STT_CONTRIBUICAO, MTD_PGT_CONTRIBUICAO, DT_CONTRIBUICAO, TB_USUARIO_ID_USUARIO, TB_MISSAO_ID_MISSAO, TB_TIER_ID_TIER) VALUES ('CONTRIB-021',65,'CONFIRMADO','PIX',DATE '2025-07-03','USR-022','MIS-007','TIER-APO')
  INTO TB_CONTRIBUICAO (ID_CONTRIBUICAO, VL_CONTRIBUICAO, STT_CONTRIBUICAO, MTD_PGT_CONTRIBUICAO, DT_CONTRIBUICAO, TB_USUARIO_ID_USUARIO, TB_MISSAO_ID_MISSAO, TB_TIER_ID_TIER) VALUES ('CONTRIB-022',550,'PENDENTE','PIX',DATE '2026-02-12','USR-023','MIS-008','TIER-CMD')
  INTO TB_CONTRIBUICAO (ID_CONTRIBUICAO, VL_CONTRIBUICAO, STT_CONTRIBUICAO, MTD_PGT_CONTRIBUICAO, DT_CONTRIBUICAO, TB_USUARIO_ID_USUARIO, TB_MISSAO_ID_MISSAO, TB_TIER_ID_TIER) VALUES ('CONTRIB-023',175,'CONFIRMADO','CREDITO',DATE '2026-02-13','USR-024','MIS-008','TIER-OPR')
  INTO TB_CONTRIBUICAO (ID_CONTRIBUICAO, VL_CONTRIBUICAO, STT_CONTRIBUICAO, MTD_PGT_CONTRIBUICAO, DT_CONTRIBUICAO, TB_USUARIO_ID_USUARIO, TB_MISSAO_ID_MISSAO, TB_TIER_ID_TIER) VALUES ('CONTRIB-024',70,'CONFIRMADO','PIX',DATE '2026-02-15','USR-025','MIS-008','TIER-APO')
  INTO TB_CONTRIBUICAO (ID_CONTRIBUICAO, VL_CONTRIBUICAO, STT_CONTRIBUICAO, MTD_PGT_CONTRIBUICAO, DT_CONTRIBUICAO, TB_USUARIO_ID_USUARIO, TB_MISSAO_ID_MISSAO, TB_TIER_ID_TIER) VALUES ('CONTRIB-025',510,'CONFIRMADO','DEBITO',DATE '2026-02-17','USR-026','MIS-009','TIER-CMD')
  INTO TB_CONTRIBUICAO (ID_CONTRIBUICAO, VL_CONTRIBUICAO, STT_CONTRIBUICAO, MTD_PGT_CONTRIBUICAO, DT_CONTRIBUICAO, TB_USUARIO_ID_USUARIO, TB_MISSAO_ID_MISSAO, TB_TIER_ID_TIER) VALUES ('CONTRIB-026',155,'PENDENTE','PIX',DATE '2026-02-18','USR-027','MIS-009','TIER-OPR')
  INTO TB_CONTRIBUICAO (ID_CONTRIBUICAO, VL_CONTRIBUICAO, STT_CONTRIBUICAO, MTD_PGT_CONTRIBUICAO, DT_CONTRIBUICAO, TB_USUARIO_ID_USUARIO, TB_MISSAO_ID_MISSAO, TB_TIER_ID_TIER) VALUES ('CONTRIB-027',85,'CONFIRMADO','CREDITO',DATE '2026-02-20','USR-028','MIS-009','TIER-APO')
  INTO TB_CONTRIBUICAO (ID_CONTRIBUICAO, VL_CONTRIBUICAO, STT_CONTRIBUICAO, MTD_PGT_CONTRIBUICAO, DT_CONTRIBUICAO, TB_USUARIO_ID_USUARIO, TB_MISSAO_ID_MISSAO, TB_TIER_ID_TIER) VALUES ('CONTRIB-028',50,'REEMBOLSADO','PIX',DATE '2025-08-05','USR-029','MIS-010','TIER-APO')
  INTO TB_CONTRIBUICAO (ID_CONTRIBUICAO, VL_CONTRIBUICAO, STT_CONTRIBUICAO, MTD_PGT_CONTRIBUICAO, DT_CONTRIBUICAO, TB_USUARIO_ID_USUARIO, TB_MISSAO_ID_MISSAO, TB_TIER_ID_TIER) VALUES ('CONTRIB-029',180,'REEMBOLSADO','DEBITO',DATE '2025-08-06','USR-030','MIS-010','TIER-OPR')
  INTO TB_CONTRIBUICAO (ID_CONTRIBUICAO, VL_CONTRIBUICAO, STT_CONTRIBUICAO, MTD_PGT_CONTRIBUICAO, DT_CONTRIBUICAO, TB_USUARIO_ID_USUARIO, TB_MISSAO_ID_MISSAO, TB_TIER_ID_TIER) VALUES ('CONTRIB-030',500,'REEMBOLSADO','CREDITO',DATE '2025-08-07','USR-021','MIS-010','TIER-CMD')
SELECT 1 FROM DUAL;

INSERT ALL
  INTO TB_HANGAR (ID_HANGAR, DT_DESBLQ_NAVE_HANGAR, STATUS_NAVE_HANGAR, NM_GRAVADO_HANGAR, TB_NAVE_ID_NAVE, TB_CONTRIB_ID_CONTRIB) VALUES ('HGR-001',DATE '2026-01-10','DESBLOQUEADA','Ana R.','NAV-001','CONTRIB-001')
  INTO TB_HANGAR (ID_HANGAR, DT_DESBLQ_NAVE_HANGAR, STATUS_NAVE_HANGAR, NM_GRAVADO_HANGAR, TB_NAVE_ID_NAVE, TB_CONTRIB_ID_CONTRIB) VALUES ('HGR-004',DATE '2026-01-10','DESBLOQUEADA','Diego M.','NAV-002','CONTRIB-004')
  INTO TB_HANGAR (ID_HANGAR, DT_DESBLQ_NAVE_HANGAR, STATUS_NAVE_HANGAR, NM_GRAVADO_HANGAR, TB_NAVE_ID_NAVE, TB_CONTRIB_ID_CONTRIB) VALUES ('HGR-007',DATE '2026-01-17','DESBLOQUEADA','Gabriela T.','NAV-003','CONTRIB-007')
  INTO TB_HANGAR (ID_HANGAR, DT_DESBLQ_NAVE_HANGAR, STATUS_NAVE_HANGAR, NM_GRAVADO_HANGAR, TB_NAVE_ID_NAVE, TB_CONTRIB_ID_CONTRIB) VALUES ('HGR-010',DATE '2026-01-22','DESBLOQUEADA','Joao P.','NAV-004','CONTRIB-010')
  INTO TB_HANGAR (ID_HANGAR, DT_DESBLQ_NAVE_HANGAR, STATUS_NAVE_HANGAR, NM_GRAVADO_HANGAR, TB_NAVE_ID_NAVE, TB_CONTRIB_ID_CONTRIB) VALUES ('HGR-013',DATE '2026-02-01','DESBLOQUEADA','Marina C.','NAV-005','CONTRIB-013')
  INTO TB_HANGAR (ID_HANGAR, DT_DESBLQ_NAVE_HANGAR, STATUS_NAVE_HANGAR, NM_GRAVADO_HANGAR, TB_NAVE_ID_NAVE, TB_CONTRIB_ID_CONTRIB) VALUES ('HGR-016',DATE '2026-02-06','DESBLOQUEADA','Paulo T.','NAV-006','CONTRIB-016')
  INTO TB_HANGAR (ID_HANGAR, DT_DESBLQ_NAVE_HANGAR, STATUS_NAVE_HANGAR, NM_GRAVADO_HANGAR, TB_NAVE_ID_NAVE, TB_CONTRIB_ID_CONTRIB) VALUES ('HGR-019',DATE '2025-07-01','DESBLOQUEADA','Tatiana C.','NAV-007','CONTRIB-019')
  INTO TB_HANGAR (ID_HANGAR, DT_DESBLQ_NAVE_HANGAR, STATUS_NAVE_HANGAR, NM_GRAVADO_HANGAR, TB_NAVE_ID_NAVE, TB_CONTRIB_ID_CONTRIB) VALUES ('HGR-022',NULL,'PENDENTE','Bianca M.','NAV-008','CONTRIB-022')
  INTO TB_HANGAR (ID_HANGAR, DT_DESBLQ_NAVE_HANGAR, STATUS_NAVE_HANGAR, NM_GRAVADO_HANGAR, TB_NAVE_ID_NAVE, TB_CONTRIB_ID_CONTRIB) VALUES ('HGR-025',DATE '2026-02-17','DESBLOQUEADA','Eduardo R.','NAV-009','CONTRIB-025')
  INTO TB_HANGAR (ID_HANGAR, DT_DESBLQ_NAVE_HANGAR, STATUS_NAVE_HANGAR, NM_GRAVADO_HANGAR, TB_NAVE_ID_NAVE, TB_CONTRIB_ID_CONTRIB) VALUES ('HGR-030',NULL,'PENDENTE','Lia C.','NAV-010','CONTRIB-030')
SELECT 1 FROM DUAL;

COMMIT;

-- Conferencia rapida da carga.
SELECT 'TB_AGENCIA' tabela, COUNT(*) total FROM TB_AGENCIA
UNION ALL SELECT 'TB_ORGANIZACAO', COUNT(*) FROM TB_ORGANIZACAO
UNION ALL SELECT 'TB_TIER', COUNT(*) FROM TB_TIER
UNION ALL SELECT 'TB_USUARIO', COUNT(*) FROM TB_USUARIO
UNION ALL SELECT 'TB_MISSAO', COUNT(*) FROM TB_MISSAO
UNION ALL SELECT 'TB_NAVE', COUNT(*) FROM TB_NAVE
UNION ALL SELECT 'TB_FASE_MISSAO', COUNT(*) FROM TB_FASE_MISSAO
UNION ALL SELECT 'TB_CONTRIBUICAO', COUNT(*) FROM TB_CONTRIBUICAO
UNION ALL SELECT 'TB_HANGAR', COUNT(*) FROM TB_HANGAR
ORDER BY 1;
