-- teste_bloco_02.sql
-- Valida o bloco_02: confirmacao de pagamento e excecao para reembolso.

SET SERVEROUTPUT ON;

PROMPT Cenario de sucesso: preparando contribuicao pendente de comandante.
UPDATE TB_CONTRIBUICAO
   SET STT_CONTRIBUICAO = 'PENDENTE',
       TB_TIER_ID_TIER = 'TIER-CMD',
       VL_CONTRIBUICAO = 600
 WHERE ID_CONTRIBUICAO = 'CONTRIB-001';
COMMIT;

SELECT ID_CONTRIBUICAO, STT_CONTRIBUICAO, VL_CONTRIBUICAO
  FROM TB_CONTRIBUICAO
 WHERE ID_CONTRIBUICAO = 'CONTRIB-001';

@@../../blocos-anonimos/bloco_02.sql

PROMPT Evidencia apos sucesso:
SELECT c.ID_CONTRIBUICAO, c.STT_CONTRIBUICAO, h.STATUS_NAVE_HANGAR, h.NM_GRAVADO_HANGAR
  FROM TB_CONTRIBUICAO c
  LEFT JOIN TB_HANGAR h ON h.TB_CONTRIB_ID_CONTRIB = c.ID_CONTRIBUICAO
 WHERE c.ID_CONTRIBUICAO = 'CONTRIB-001';

PROMPT Cenario de excecao: contribuicao reembolsada nao pode ser confirmada.
UPDATE TB_CONTRIBUICAO
   SET STT_CONTRIBUICAO = 'REEMBOLSADO'
 WHERE ID_CONTRIBUICAO = 'CONTRIB-001';
COMMIT;

@@../../blocos-anonimos/bloco_02.sql

UPDATE TB_CONTRIBUICAO
   SET STT_CONTRIBUICAO = 'CONFIRMADO'
 WHERE ID_CONTRIBUICAO = 'CONTRIB-001';
COMMIT;
